### ISSUE TITLE
algolia:reindex error :  A slave index is already slave of another index

### ISSUE THREAD

**Issue by odecharette** [algolia/search-bundle#102]
Hi,

When I reindex my entity with the command `php bin/console algolia:reindex BecowoMemberBundle:Membe` I get the error 

> [AlgoliaSearch\AlgoliaException]
A slave index is already slave of another index

I found a solution but it's heavy !
I delete the replica of my index in the dashboard
Then reindex my entity
Then redo the replica in the dashboard

Any help ?
Thanks

**Comment by julienbourdeau** [comment]
Hi @odecharette,
Can you give us more details about your configuration? Like the index settings and anything you feel might be important. 
I think you're solution is the good one. I'll look deeper when I have more details :)
