### ISSUE TITLE
Embedded objects (incl. Doctrine embeddables) are not indexed

### ISSUE THREAD

**Issue by samjarrett** [algolia/search-bundle#123]
I've got a doctrine entity that makes use of Doctrine's `@Embeddable` objects.  When I index the entities (using either the Manual Indexer, the Automatic Indexer, or the reindex command), embedded objects end up as null values.

Upon investigation, I noticed that `Algolia\AlgoliaSearchBundle\Indexer\Indexer::isEntity()` currently enforces only scalar values and Doctrine entities to be indexed, and not other miscellaneous objects, regardless of whether the objects have `@Algolia\Index` or `@Algolia\Attribute` annotations.

Wondering if this is intentional?

**Comment by alcaeus** [comment]
@samjarrett What would you expect to happen? Would you expect fields from the embeddable to be directly included in the indexed document (similar to how the columns are added to the database table) or as a nested object (similar to how embedded documents are treated for MongoDB ODM?)

**Comment by samjarrett** [comment]
Hey @alcaeus, I would expect that it would try to serialise them like it does a regular entity that you're including as an attribute?

**Comment by kiler129** [comment]
FYI for anyone looking here - `v3` supports embeddables when groups are properly defined.

Shouldn't we close this, since v2 is EOL?

**Comment by julienbourdeau** [comment]
Yes @kiler129 I agree. Thanks!
