### ISSUE TITLE
Support Symfony 4.0

### ISSUE THREAD

**Issue by aequasi** [algolia/search-bundle#137]

**Comment by julienbourdeau** [comment]
Hi @aequasi,

I'm testing the bundle on the [symfony/demo](https://github.com/symfony/demo) project and so far it worked pretty well. Did you run into any particular issue?

**Comment by alcaeus** [comment]
@julienbourdeau composer.json does not allow for Symfony 4.0 packages to be installed - not sure how you managed to test it against Symfony 4 ;)

**Comment by julienbourdeau** [comment]
I used Symfony Flex since we have a [contrib recipe](https://github.com/symfony/recipes-contrib/tree/master/algolia/algolia-search-bundle/2.2). I didn't think about not using Flex 😄

**Comment by alcaeus** [comment]
You can use flex for it - as long as you started with Symfony 4 the results should be the same as without flex. The problem is not flex, the problem is the allowed set of dependencies.

**Comment by julienbourdeau** [comment]
I'm currently thinking that the `2.x` version will remain compatible with Symfony 3.x while the new 3.0 version will be dedicated to 3.4 and 4.x version. I'll write the upgrade guide but it should be pretty straight forward.

If you get to try the 3.0 version, I'd love to here your feedback.

**Comment by aequasi** [comment]
Upgrading to allow 4.0 shouldn't break BC, from what I've seen. Not much need for a major version increment. That being said, if you dont want to support 2.x or symfony 3.x then that works

**Comment by nmeirik** [comment]
Not supporting 3.4 poses a problem, upgrade-wise, since upgrading an older installation to Symfony 4.x requires going via 3.4 in order to sort out the deprecations.

Installing the current 3.x BETA (3.0.0-BETA3) on Symfony 3.4 does not appear to work.

**Comment by julienbourdeau** [comment]
@nmeirik I'll check again but 3.x should definitely be compatible with Symfony 3.4 👌 Don't hesitate to open issues with bugs or feedbacks.

**Comment by julienbourdeau** [comment]
@nmeirik Can you open issues and show what issue you encounter? I tried `3.4` and it seems to work as expected.

**Comment by nmeirik** [comment]
@julienbourdeau I'm sorry for not making sufficient notes with regards to what I deemed not to work.

My time does not currently allow time for a new upgrade attempt, so please disregard my comment. Should I encounter issues when upgrading again, I will specify those (properly) in a separate issue.

**Comment by aequasi** [comment]
The biggest issue i've seen is the lack of the `IndexIf` annotation.

**Comment by julienbourdeau** [comment]
Yes, I'll think about a way to add that. Do you mind opening a separate issue for it?

**Comment by aequasi** [comment]
Finished. Feel free to close this if you want.

**Comment by seyi-adetunji** [comment]
Hi Everyone,
                    Please, I am trying to use Algolia with Symfony 3.4 and after following the configuration instructions, I encountered this error "The service "search.index_manager" has a dependency on a non-existent service "serializer"". Please, can anyone assist?

**Comment by tristanbes** [comment]
you need to enable the `serializer` component under the `framework` namespace (in your `config.yml` file:

- https://symfony.com/doc/3.4/serializer.html#activating-the-serializer
- https://symfony.com/doc/current/reference/configuration/framework.html#serializer
