### ISSUE TITLE
[3.0] Non-existent service "search.index_manager" on prod env

### ISSUE THREAD

**Issue by tristanbes** [algolia/search-bundle#146]
When running

`bin/console search:import <entity> --env=dev` -> does the job.
`bin/console search:import <entity> --env=prod` -> throws an error.

```
You have requested a non-existent service "search.index_manager"
```

<img width="1420" alt="1__app_seek-team___srv_app__ssh_" src="https://user-images.githubusercontent.com/346010/33489664-d2a9e222-d6b4-11e7-94e3-4ae5eacbce1c.png">

**Comment by tristanbes** [comment]
Huh, this one's on me. Forgot to cache clear

**Comment by julienbourdeau** [comment]
Happens to me all the time :D
