### ISSUE TITLE
[3.0] Number of indexed entities is not correct

### ISSUE THREAD

**Issue by tristanbes** [algolia/search-bundle#154]
In case of your normalizer add some logic to exclude an entity from being index you got the wrong numbers.

In my example, I got 45,000 indexed entities displayed out the console, but when I go inside the algolia dashboard, it's only 17,000 that are in the index. It can be confusing for the end user.

IMHO the counter that needs to be displayed on the terminal should be a counter pulled from the AgloliaEngine where the actual calls are made (and where we filter out empty arrays after #150 is getting merged)

**Comment by julienbourdeau** [comment]
Indeed, I think I found a good solution that keeps the bundle agnostic. I opend the PR #195, feel free to try it and provide feedback.
