### ISSUE TITLE
Packagist refers to wrong version for dev-master

### ISSUE THREAD

**Issue by tristanbes** [algolia/search-bundle#161]
It's been 10 minutes i'm trying to find a regression but it's just that packagist didn't update the package.

Maybe you forgot to set the auto update hook ?

dev master still points to the SHA1 commit of BETA-2
see: https://packagist.org/packages/algolia/search-bundle#dev-master

**Comment by julienbourdeau** [comment]
Yes packagist was not yet setup. The hook was used with the former name `algolia/algolia-search-bundle` and since we use the same GitHub repository we cannot have them both auto-updating. I switch so now, the legacy name is not auto-update but this one is.
