### ISSUE TITLE
State on MongoDB support

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/search-bundle#164]
Currently, if you have entities managed with MongoDB and MySQL (for instance), the data will be updated by the doctrine events and search works properly. this is because the ObjectManager is injected by the user or by the framework.

So far, only the [batch import command](https://github.com/algolia/search-bundle/blob/master/src/Command/SearchImportCommand.php#L26) `php bin/console search:import ENTITY_NAME` doesn't work. It will require something to know whether the entity is managed by ERM or ODM.

Any suggestions?

**Comment by alcaeus** [comment]
You should check both `doctrine` and `doctrine_mongodb` services and handle them equally if they are present.

**Comment by julienbourdeau** [comment]
In the following example:

```php
$doctrine = $this->getContainer()->get('doctrine');
$doctrineMongo = $this->getContainer()->get('doctrine_mongodb');

$repository = $doctrine->getRepository($entityClassName);

$manager = $doctrineOrDoctrineMongo->getManager();
```

How do I know on which doctrine to call `getManager()`?

**Comment by alcaeus** [comment]
Both services are manager registries: you fetch the manager from the registry, then fetch the repository from that. Calling `getRepository` with only an entity name will produce invalid results when using multiple EntityManagers, even if you don't add ODM to the equation.

In short:
```
$doctrine = $this->getContainer()->get('doctrine');
$doctrineMongoDB = $this->getContainer()->get('doctrine_mongodb');

$manager = $doctrine->getManagerForClass($entityClassName);
if (!$manager) {
    $manager = $doctrineMongoDB->getManagerForClass($entityClassName);
}

$repository = $manager->getRepository($entityClassName);
```

You can also create a registry chain that looks in a set of manager registries to return the correct manager for a class. Unfortunately, both ORM and ODM bundles currently create separate registries, a fact that can't easily be rectified with BC breaks in both bundles, so you'll have to roll your own combined registry.

**Comment by hhmmrrhh** [comment]
Discuss
