### ISSUE TITLE
Algolia : sort By date // Which format to use for DateTime

### ISSUE THREAD

**Issue by tristanbes** [algolia/search-bundle#165]
I'm asking this there, because I know user will ask the same question in the future

When manipulating a date through built-in Symfony Normalizer, without any options, algolia recieves: 
`"2018-03-27T01:00:48+00:00"`

But then, it's impossible to sortBy this field because it only accepts boolean or numerical. 
So, **which date format I need to pass to the normalizer** to have a datetime that Algolia can understand ? 

example: 
```php
$serializer->normalize(
    new \DateTime(),
    null,
    array(DateTimeNormalizer::FORMAT_KEY => 'Y/m')
);
```

Thanks

**Comment by tristanbes** [comment]
Did you had time to check this question @julienbourdeau ?

**Comment by julienbourdeau** [comment]
Great question, I should add some usecase like this in the doc! Thanks for showing the way with `DateTimeNormalizer::FORMAT_KEY`. 

If you want to use the attribute for **sorting**, converting ti timestamp is a great way `DateTimeNormalizer::FORMAT_KEY => 'U'`. 

If you want to use the date in your **custom ranking**, it's recommended to create ties and have another metric after that. In general, an article published 6 seconds before another one doesn't make it more important. So depending on your use case, if you want consider all articles of the same day equals, it's best to use a format like `Y-m-d`. If you want to consider all articles of the same week equals, per week you can use `Y-W`.

If you want to create a attribute for facets, you can use a string format that would group articles as you wish.

Please let me know if it's clear enough.

**Comment by tristanbes** [comment]
Well **custom ranking** accepts only integer or boolean and not a string. So formating a date like `Y-m-d` won't work.

I guess i'm gonna go with `$object->getUpdatedAt()->getTimestamp()`

**Comment by julienbourdeau** [comment]
Indeed! Then you can remove the `-` and cast it to make sure it's an _int_.

**Comment by hhmmrrhh** [comment]
v3

**Comment by hhmmrrhh** [comment]
#165

**Comment by hhmmrrhh** [comment]
Yfug
