### ISSUE TITLE
[3.0] be resilient to Doctrine not being there

### ISSUE THREAD

**Issue by rayrutjes** [algolia/search-bundle#175]
![image](https://user-images.githubusercontent.com/5570853/34301310-5a61a308-e72c-11e7-9c78-71f934fe6bc8.png)

**Comment by julienbourdeau** [comment]
I looked into it but actually Doctrine should be an requirement for the bundle, I'll move it from `require-dev` to `require`.
It's needed for indexing commands and search, not only for the event subscriber.

Thanks Ray for spotting it.
