### ISSUE TITLE
[3.0] put tests in src/Tests

### ISSUE THREAD

**Issue by rayrutjes** [algolia/search-bundle#176]
Following Bundle recommendations here: https://symfony.com/doc/current/bundles.html#bundle-directory-structure

**Comment by julienbourdeau** [comment]
Thanks for pointing it out!
I thought about it a lot. In the end, I'd rather not change the bundle structure. I found some very popular bundle ([here](https://github.com/FriendsOfSymfony/FOSElasticaBundle), [here](https://github.com/sonata-project/SonataAdminBundle), [here](https://github.com/KnpLabs/KnpMenuBundle) <-- even Stof 😁) that don't follow this structure so I think I'll keep it like this.
