### ISSUE TITLE
[3.0] better configuration management

### ISSUE THREAD

**Issue by rayrutjes** [algolia/search-bundle#178]
It would be nice to offer a `config/packages/algolia_search.yml` file by default to set the Algolia Credentials.

We could even create one in `config/packages/dev/algolia_search.yml` that adds a prefix of `dev_`.

**Comment by julienbourdeau** [comment]
Having a default file with prefix is a good idea. It would encourage people to change it.

About credentials, you can't store them here, because this file is committed.

**Comment by tristanbes** [comment]
Just don't forget 3.4 user that don't follow 4.0 architecture please :-)

**Comment by julienbourdeau** [comment]
The default configuration is now handled by Symfony Flex, so I believe this issue can be closed.
https://github.com/symfony/recipes-contrib/pull/244/files
