### ISSUE TITLE
How to inject search.index_manager in constructor (when it's not in container)

### ISSUE THREAD

**Issue by JacobDelcroix** [algolia/search-bundle#185]
Hi,

Can't make this bundle works on Symfony 4. Do you have any idea? It should works with Symfony 3.4 and higher according to the documentation.
When trying to fetch the search.index_manager from container (or inject it with autowire) I always have an error.

I'm using 3.0.0-BETA4 rev.

**Comment by julienbourdeau** [comment]
What error do you have? Can you share the code snippet as well please, I'd be happy to help.

**Comment by JacobDelcroix** [comment]
Thanks for your response @julienbourdeau .

Here is my composer.json:
` "algolia/search-bundle": "^3.0@beta",`

Then when I try to fetch index_manager in my controller
`$this->get('search.index_manager');`

I got

> Service "search.index_manager" not found: even though it exists in the app's container, the container inside "App\Controller\Dashboard\PagesController" is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "request_stack", "router", "security.authorization_checker", "security.token_storage", "serializer", "session" and "twig" services. Unless you need extra laziness, try using dependency injection instead. Otherwise, you need to declare it using "PagesController::getSubscribedServices()".

I know in SF4 you can inject services within your controller params, so I my __contruct method I try:
```
public function __construct(IndexManager $indexManager)
{
        $this->indexManager = $indexManager;
}
```

But i got:

> Cannot autowire service "App\Controller\Dashboard\PagesController": argument "$indexManager" of method "__construct()" references class "Algolia\SearchBundle\IndexManager" but no such service exists. It cannot be auto-registered because it is from a different root namespace.

**Comment by julienbourdeau** [comment]
Can you try to declaire this in your `services.yml` (and keep injecting it in the constructor):

```yaml
services:
    Algolia\SearchBundle\IndexManager:
        alias: search.index_manager
```

Is there anyway you could give me access to the source? I cannot reproduce it with the `symfony/demo` project. Apparantly Sf4 has a lighter container, it's not a best practice to get everything from it anymore, it should be injected (like you did).

**Comment by JacobDelcroix** [comment]
Thanks for your help. Error is gone but I can't test if everything is working as expected (I'm out of office). I will give it a try thuesday :-)

**Comment by romainnorberg** [comment]
hello @JacobDelcroix @julienbourdeau it's work for me (3.0.0-BETA4).
- declare in `services.yaml`
- injecting it in the constructor
👍

**Comment by julienbourdeau** [comment]
I will declare the alias in the bundle #186 

It shouldn't break anything if you declare it in your services.yaml but feel free to test it and comment.
