### ISSUE TITLE
[3.0] Failure after installation due to variable not found

### ISSUE THREAD

**Issue by tristanbes** [algolia/search-bundle#199]
Hello,

Is it intended to fail right after installation ? Shouldn't we provide those keys in an interactive way ?

**Comment by tristanbes** [comment]
![1__app_eqiom___srv_app__ssh_](https://user-images.githubusercontent.com/346010/34822673-fd9e1be6-f6c7-11e7-806b-f4ce136ae941.png)

**Comment by julienbourdeau** [comment]
I'd rather leave that [in the flex recipe](https://github.com/symfony/recipes-contrib/pull/244/files#diff-fdf6a12ea5b80e434253f55d6fd6ffdaR11) but I agree this is not a great experience, I'll see how I can handle it nicely.

**Comment by julienbourdeau** [comment]
I cannot reproduce this issue with Flex. I'm also hoping #218 fixed it if you don't use Flex.
