### ISSUE TITLE
Conditionally index entities

### ISSUE THREAD

**Issue by aequasi** [algolia/search-bundle#202]
It would be nice to be able to conditionally index entities based on specific criteria (like a field returning true or false) like the only lib allowed for.

**Comment by aequasi** [comment]
The `search:import` command should also de-import any entities that are marked against indexing

**Comment by julienbourdeau** [comment]
Hi @aequasi,

I opened this PR #210  to add the index_if feature. I'd really appreciate if you could review it.

The main question I had, was either this check should be in `IndexManager->index()` or higher, in the import command.
