### ISSUE TITLE
Allowed memory size exhausted during search:import

### ISSUE THREAD

**Issue by brunonic** [algolia/search-bundle#206]
I'm trying to `search:import` my products (37 000) and I got this error : 

    php bin/console search:import --indices=product

    PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes) in .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58
    Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes) in .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58
    PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in .../vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1
    Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in .../vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1

I'm using `algolia/search-bundle": "^3.0`

To much entries ?

**Comment by julienbourdeau** [comment]
Yes but it's definitely a big, this should be paginated to avoid this. Thank you for creating this issue, I'll take care of it ASAP!

**Comment by brunonic** [comment]
There is no replacement for algolia:reindex ? I have never had a problem with.

**Comment by julienbourdeau** [comment]
Do you mean clear and reimport in one command?

Would you mind testing this PR #208 and let me know if that fix your issue?
I added a config key `batchSize` with a default of 500. Feel free to test smaller values if necessary.

Thanks!

**Comment by brunonic** [comment]
This PR fix my issue.

Thanks!
