### ISSUE TITLE
search:settings:backup and Symfony4 directory structure

### ISSUE THREAD

**Issue by brunonic** [algolia/search-bundle#207]
I'm trying to backup my settings with `search:settings:backup`. Import is ok but in a `app\Resourses` folder. In Symfony4 there is no more app folder.

**Comment by julienbourdeau** [comment]
With Symfony 4 it should be backed up un `/config/settings/algolia_search/`

Is it a Sf 3 app upgrade to Sf4 or is a fresh install? Do you get an error message (if so, please add a screenshot).

Thanks for reporting this issue!

**Comment by brunonic** [comment]
Oh sorry for this project I'm on a 3.4.4 with a Symfony 4 Flex Directory Structure

**Comment by julienbourdeau** [comment]
Oh yeah I see.
I'm not sure how to handle this. Should we _detect_ the directory structure, regardless of the Sf version or is there a better way?

Today I was sort of hoping that project started with Flex will be using Sf4 ^^
https://github.com/algolia/search-bundle/blob/master/src/DependencyInjection/AlgoliaSearchExtension.php#L37

**Comment by brunonic** [comment]
I have upgrade my project to Sf4, now it work fine. The Sf3.4 install come with a flex1.0 .
Flex is available from Sf3.3.
