### ISSUE TITLE
Support Message component when released

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/search-bundle#214]
When/If this is merged https://github.com/symfony/symfony/pull/24411 the bundle should support it.

**Comment by tristanbes** [comment]
What do you have in mind by "support it" ?

**Comment by julienbourdeau** [comment]
Not sure yet but something like, turn the feature on, all call to algolia are added to a queue. 
Sort of like [Laravel Scout does it](https://laravel.com/docs/5.6/scout#queueing).
