### ISSUE TITLE
Add required php extensions in composer.json

### ISSUE THREAD

**Issue by arteniioleg** [algolia/search-bundle#217]
[Like here](https://github.com/algolia/algoliasearch-client-php/blob/e2afbf8863b5a5bd3d9fba3c008e625f7430bde7/composer.json#L23)

On `composer install` on my production machine I got

```
Script cache:clear returned with error code 1
!!  
!!  In Client.php line 80:
!!                                                    
!!    AlgoliaSearch requires the CURL PHP extension.
```

**Comment by julienbourdeau** [comment]
Hi @arteniioleg,
Thanks for filing this bug. I think it should be added to the client, since this is where it's required. I'm not sure why it wasn't added before. I'll have a look.

https://github.com/algolia/algoliasearch-client-php/blob/master/composer.json#L23

**Comment by julienbourdeau** [comment]
I'll close this issue and we can discuss it on algolia/algoliasearch-client-php#384. Thanks @OskarStark for opening the PR. 👌
