### ISSUE TITLE
Application is crashing if Algolia's number of operations is exceeded

### ISSUE THREAD

**Issue by JosephELKHOURY** [algolia/search-bundle#222]
Hello,

Whenever we exceed the number of operations, the symfony application starts crashing when we use the endpoints related to the entity that is indexed in Algolia.

I couldn't find any way to fix this. How can we prevent it?

At least you should ignore indexing when number of operations is exceeded.
What do you think?

**Comment by julienbourdeau** [comment]
I think the algolia client will raise an exception if you reach the quota but I'm not sure who should be catching it. If it's the bundle reponsability, what behavior do we want? We could log the error in prod env and fail on dev env. 
Is that what you had in mind?

**Comment by JosephELKHOURY** [comment]
That would be good because we're having the crash on the prod website and it's really disturbing.
And I guess you can also do the same on dev. What do you think?

**Comment by julienbourdeau** [comment]
Do you mean logging in dev too instead of crashing? In dev env, I like when it crashes because I think it's the best way to avoid issue in prod. I'm affraid to many people won't read the logs in dev.

**Comment by JosephELKHOURY** [comment]
You have a point (Y)

**Comment by julienbourdeau** [comment]
I have discussed this with the team, I the error message from Algolia are not part of the public API so they can change without prior notice. Parsing the error message to throw a certain type of error message is then error prone. The HTTP error code is much more stable but the one for quota issues is used for all type of similar error (rate limit for instance).

In the end, I believe the best way would be to catch it on your side. Note that most method with Algolia could throw an `AlgoliaException` so it should be caught.

Please let me know if you have any related question or need more guidance to deal with that. I'd be happy to help.
