### ISSUE TITLE
[RFC] Add symfony 4.x to Algolia/search-bundle 2.x

### ISSUE THREAD

**Issue by Simperfit** [algolia/search-bundle#223]
We would like to update to symfony 4.x without upgrading to Algolia/search-bundle to 3.x since we decorated the commands to add our own feature.

Could it be possible to accept a PR adding the support of Symfony 4.x to algolia/search-bundle 2.x ?

Thanks.

**Comment by julienbourdeau** [comment]
I understand why it's more work for you to upgrade could you share what your commands are doing and if there is anything we could add to the bundle?

I'm afraid that if the version 2.x supports Sf4, we'll to keep supporting 2.x (pretty much) forever.

Just to be sure, appart from the decorated command, is there anything else that prevent you from upgrading?

**Comment by julienbourdeau** [comment]
@Simperfit I'm really not keen to keep maintaining the v2 today. In the past few months I wasn't able to work on it as much as I wanted to. I don't think it's a good idea.

Could you tell me what you did with v2 and what you need to be able to migrate?

**Comment by Simperfit** [comment]
We, at the end, updated and refactored the commands ^^. So This is not an issue anymore.
