### ISSUE TITLE
Using Algolia with JMS serializer

### ISSUE THREAD

**Issue by silasjoisten** [algolia/search-bundle#224]
Algolia version
```console
www-data@f15ea50d0cf3:~$ composer show algolia/*
algolia/algoliasearch-client-php 1.25.1 
algolia/search-bundle            3.1.1
```
Symfony version
```console
www-data@f15ea50d0cf3:~$ composer show symfony/symfony
symfony/symfony            v3.4.3 
```
PHP 7.1.15

### Description
I try to integrate Algolia in my sonata project. The problem is that algolia-bundle uses symfony default serializer and sonata uses JMS Serializer. How i can change from default Serializer to JMS serializer?

**Comment by julienbourdeau** [comment]
Hm very good question! I'll look into it, I think it should be doable 👍

**Comment by janjango** [comment]
I have the same problem:
 `Argument 1 passed to Algolia\SearchBundle\IndexManager::__construct() must implement interface Symfony\Component\Serializer\Normalizer\NormalizerInterface, instance of JMS\Serializer\Serializer given`

I'm using:

```
algolia/search-bundle            3.1.2 
symfony/symfony v3.4.6
```

**Comment by julienbourdeau** [comment]
@janjango Have you tried the PR #225? Did it fix your issue?
