### ISSUE TITLE
Add search:clear command usage example in documentation

### ISSUE THREAD

**Issue by gabhwc** [algolia/search-bundle#226]
- Symfony version: 4.0.4
- Algolia Search Bundle version: 3.1.1
- Algolia Client Version: 1.23.0
- Language Version: 7.1

### Description

There is currently no mention of `search:clear` command in README.md. A quick usage guide could be added either:
- in the "3. Indexing" section
- in the "7. Advanced" section
- in a new "7. Deindexing" section

Discovered it while trying to implement the feature by extending the `IndexCommand`. Happy to do a PR, couple of questions though: 
- Is there any reason for this command not being mentioned (plan to remove the feature, unstable, cost of deindexing/reindexing operations, or else)?
- Is there a plan to allow the community to do PR on the documentation?

PS: first issue on this account 🎉 . Congrat's for v3 of the bundle, it is super neat for my use!

**Comment by julienbourdeau** [comment]
Thanks! :)

There is no reason to not mention this command, I don't know how I missed it  ^^ I will add it right away.

Today the repository with the doc is private, I hope one day we can open it but I don't think it will be soon.

**Comment by julienbourdeau** [comment]
It was merged today, it be live next time the doc is deployed.
