### ISSUE TITLE
Group feature (annotations) are not working when deleting an entity

### ISSUE THREAD

**Issue by lemonlab** [algolia/search-bundle#227]
- Symfony version: 3.4.4
- Algolia Search Bundle version: 3.1.1
- Language Version: PHP 7.1.13

### Description
The annotations `@Groups({"searchable"})` are not taken into account when deleting an entity.

### Steps To Reproduce
- Create 2 entities `A` and `B`
- Create a circular reference between `A` and `B` (2 way relationship)
- Index one field in the entity `A` that is not part of the circular reference with the annotation `@Groups({"searchable"})`
- Configure Algolia to use the Serializer group : `enable_serializer_groups: true`
- Remove the entity `A` using the entity manager

Symfony will throw an exception, even if the field responsible of the circular reference is not supposed to be indexed by Algolia.
```
In AbstractNormalizer.php line 193:

  [Symfony\Component\Serializer\Exception\CircularReferenceException]
  A circular reference has been detected when serializing the object of class "CosmeticsBundle\Entity\Ingredient" (configured limit: 1)
```

**Comment by Cevantime** [comment]
Same problem here !

**Comment by arteniioleg** [comment]
Thanks. This fixed circular reference for me too. On entity form update I have a `CollectionType` field to edit `OneToMany` relation.
