### ISSUE TITLE
Prefix per environment not taken into account

### ISSUE THREAD

**Issue by sylvain-h** [algolia/search-bundle#229]
Hello,

The bundle doesn't seem to use the prefix per environment setup when searching in an index (the env prefix does not show up).

I'm gathering more details on behalf on the developer but is there any chance it is the same as issue https://github.com/algolia/search-bundle/issues/92 (or directly linked to it)?

Thanks

**Comment by julienbourdeau** [comment]
I understand that this is related to the v2. The doc is now only availbale in the README of the `2.x` branch. Can you confirm that `@Algolia\Index(perEnvironment=true)` is set as stated here: https://github.com/algolia/search-bundle/tree/2.x#per-environment-indexing
