### ISSUE TITLE
Automatic Dates Conversion

### ISSUE THREAD

**Issue by kiler129** [algolia/search-bundle#247]
- Symfony version: 4.1.3
- Algolia Search Bundle version: 3.2.0
- Algolia Client Version: 
- Language Version: 7.2.8

### Description
Algolia [does not support date search](https://www.algolia.com/doc/tutorials/full-text-search/filtering-faceting/android/#filter-by-date) and requires [manual conversion to timestamps](https://www.algolia.com/doc/guides/searching/filtering/#filter-by-date). 

What if we can add (optional) automatic `\DateTimeInterface` conversion to timestamps, which can be enabled in config? This is pretty simple addition on the bundle side actually.

WDYT?

**Comment by julienbourdeau** [comment]
Hi @kiler129,
I wouldn't mind adding more normalizer to the bundle, but it's not easy to make one that always does what you want. 

Timestamp is actually not the only way to filter with Algolia. You can format the date in very different ways with Algolia. Timestamp is good but you want to show resulsts for one month, or one week, you could have

```json
{
    "date": {
        "month": 201808,
        "week": 201834
    }
}
```

Then you can filter with `filters: date.month=201808` to show all matching results in August 2018 or  `filters: date.week=201834` to show all matching result for week 34.

If you use a date in your custom ranking, I'd also recommend not to use timestamp but something like the above, in order [to create ties](https://www.algolia.com/doc/guides/ranking/ranking-formula/#tie-breaking-approach).

Please let me know what you think and share your usecase if you think this doesnt help.


I wrote some documentation about how to use a custom normalizer: https://www.algolia.com/doc/api-client/symfony/customizing/?language=symfony#using-a-custom-normalizer
Let me know if you need more details.

**Comment by julienbourdeau** [comment]
I'm closing this issue but feel free to comment and tell me what you think, I'll reopen it if necessary 👍
