### ISSUE TITLE
AlgoliaEngine Serialized Entities Twice

### ISSUE THREAD

**Issue by kiler129** [algolia/search-bundle#253]
- Symfony version: 4.1.3
- Algolia Search Bundle version: `master`
- Algolia Client Version: ?
- Language Version: 7.2.9

### Description
While writing my own engine implementation (to log arrays on `dev` for debugging) I looked into source implementation:

https://github.com/algolia/search-bundle/blob/af07217884658d088e50e815c79bf0c0bf9a9af7/src/Engine/AlgoliaEngine.php#L91-L101

This seems rather odd in terms of performance. Is there a reason to serialize entity twice (which with complicated normalizers can stress the server significantly)?

IMHO I think `SearchableEntityInterface::getSearchableArray()` shouldn't be called twice.

**Comment by julienbourdeau** [comment]
Hi @kiler129 
You're right, I'll fix it today 👍 Thanks for taking the time to report it.
