### ISSUE TITLE
[Bug] Entity::getId() Should Be Serialized via Serializer 

### ISSUE THREAD

**Issue by kiler129** [algolia/search-bundle#261]
- Symfony version: v4.1.x
- Algolia Search Bundle version: 
- Algolia Client Version: 3.3.1
- Language Version: 7.2

### Description
The bundle makes half-assumption about entities identifiers, assuming they are strings (and in the worst case scenario types directly castable to strings).

The offending part of the code exists in `AlgoliaEngine::doUpdate()` method:
https://github.com/algolia/search-bundle/blob/bf8649b1401a757feac92bd5b1d91557b37658c5/src/Engine/AlgoliaEngine.php#L96-L109

as well as partially in `SearchableEntity::setId()` implementation:
https://github.com/algolia/search-bundle/blob/bf8649b1401a757feac92bd5b1d91557b37658c5/src/SearchableEntity.php#L61

### How it works now
Current solution works with identifiers which are objects kind of by accident:
https://github.com/algolia/algoliasearch-client-php/blob/master/src/AlgoliaSearch/Index.php#L116-L118

This code in raw API client casts object, and if it contain `__toSring()` method it will work. However this behavior cannot be really relied on and is hard to modify, since the bundle skips whole serializer.
For example very popular `Ramsey/Uuid` library specifies `UuidInterface` without `__toString()` (but with `toString()`).

### Solution
While handling identifier coming from Doctrine's `getIdentifierValues()` you need to assume that it may not be a string and may require additional transformation. I will recommend calling `\is_scalar()` first and casting all scalars to string using `(string)`. However if the check returns false let serializer handle the serialization of id.

**Comment by nunomaduro** [comment]
@kiler129 Thanks for reporting this issue! 👍

Since you already have a proposal, can you **work on a Pull Request**? If you want I can later add tests into it.

**Comment by kiler129** [comment]
Sure, I will be happy to submit a PR.

I usually do TDD, so tests will be included ;)

**Comment by kiler129** [comment]
@nunomaduro PR ready. I hope you like it ;)

**Comment by chloelbn** [comment]
I'm closing this issue as the related PR has been closed too. 
@kiler129, if you would still like to make a PR, don't hesitate and submit it to us! We released the v4 just today, it would be awesome if you checked the [upgrade guide](https://github.com/algolia/search-bundle/blob/master/UPGRADE-4.0.md) and started from here! It's still an alpha so feedbacks are very much welcome.

Have a good day!
