### ISSUE TITLE
Exception : AlgoliaSearch requires the CURL PHP extension

### ISSUE THREAD

**Issue by eved42** [algolia/search-bundle#268]
- Symfony version: 4.1
- Algolia Search Bundle version: 3.3
- Algolia Client Version:
- Language Version:

### Description
After indexing my entities, I go on my home page and I have an Exception : 
```
AlgoliaSearch requires the CURL PHP extension.
in Client.php line 80
```

I checked and I already have the CURL extension with Wampserver. This extension is enabled and I have the `php_curl.dll` file in my php folder.

I also have this line in my php.ini  :
 `extension=php_curl.dll`

**Comment by julienbourdeau** [comment]
Can you check your configuration with the phpinfo function?
http://php.net/manual/fr/function.phpinfo.php
Is curl shown enabled?

**Comment by kiler129** [comment]
@julienbourdeau Aside from this it's probably good idea to define both minimum PHP version (I created 3 PRs - I still have no idea which one to target and I guess 5.6 because of Travis :P) and required extensions.

This will redirect support questions to general PHP or composer-related SO questions :)

**Comment by alcaeus** [comment]
@kiler129 be the change you want to see in this world: #289.

As for the CURL requirement, this bundle doesn't use curl at all. The underlying client does and it properly exposes the dependency in its package configuration: https://packagist.org/packages/algolia/algoliasearch-client-php#2.2.0.

**Comment by chloelbn** [comment]
Thanks for the good job everyone! I'm closing this issue now
