### ISSUE TITLE
timeout parameter(s)

### ISSUE THREAD

**Issue by bonswouar** [algolia/search-bundle#278]
Previously there was a `connection_timeout` parameter, which doesn't exist anymore. See https://github.com/algolia/search-bundle/pull/106

IMO we should even include the read & write timeout, see https://www.algolia.com/doc/api-reference/api-methods/configuring-timeouts/?language=php
EDIT : Oh, just saw that `writeTimeout` is "Only available for the following languages: javascript, csharp."

**Comment by nunomaduro** [comment]
Thanks for bringing this to my attention. You are right! This is a good to have feature.

Do you want work in a Pull Request for this? Any idea for the implementation?

**Comment by bonswouar** [comment]
I was thinking about a `.env` global parameter.
But now that I give it a thought I guess some use cases would need to customize more programmatically, for example a method in the `indexManager` service and an optional parameter in the command(s).
What do you think ?

**Comment by chloelbn** [comment]
Hello @bonswouar, sorry for the delay to reply to your issue.
We just released the [Search Bundle v4 alpha 2](https://github.com/algolia/search-bundle), which integrates our [PHP Client v2](https://www.algolia.com/doc/api-client/getting-started/install/php/?language=php) 🎉!!

Thanks to this new version, you can now make direct calls to the `SearchClient`, which has become public. That means to still be able to use `connection_timeout`, one solution could be to create a new service instantiating a `SearchClient` with your custom `SearchConfig`, and to overrides the `search.client` service with your new one.

Below is an example

```
// App/Service/AppService.php
<?php

namespace App\Service;

use Algolia\AlgoliaSearch\Config\SearchConfig;
use Algolia\AlgoliaSearch\SearchClient;

class AppService
{
    public static function getClient()
    {
        $config = SearchConfig::create(getenv('ALGOLIA_APP_ID'), getenv('ALGOLIA_API_KEY'));
        $config->setConnectTimeout(2);
        $config->setReadTimeout(30);
        $config->setWriteTimeout(30);
        return SearchClient::createWithConfig($config);
    }
}
```

```
// config/services.yaml
services:
  # ...
  search.client:
    class: Algolia\AlgoliaSearch\SearchClient
    factory: ['App\Service\AppService', 'getClient']
```

I'm closing this issue, don't hesitate and reopen it if it doesn't solve your problem.

Also, **we really encourage you to try and play around with our new v4** ✨ ! You can find the [upgrade guide here](https://github.com/algolia/search-bundle/blob/master/UPGRADE-4.0.md). It's still in alpha version so any feedbacks are more than welcome!

Happy coding!
