### ISSUE TITLE
How to rename indexed attribute?

### ISSUE THREAD

**Issue by Cypaubr** [algolia/search-bundle#284]
- Symfony version: 3.4
- Algolia Search Bundle version: 3.4.0
- Algolia Client Version: 1.28.0
- Language Version:

Is there a way to rename  indexed attributes like `@Algolia\Attribute(algoliaName="_geoloc")` on the old bundle in this bundle?

**Comment by nunomaduro** [comment]
@Cypaubr The records it's already indexed? You will need to re-import your data.

**Comment by Cypaubr** [comment]
@nunomaduro Obviously you did not understand what I wrote. I am moving from the old bundle to the new. In the old bundle, I could rename indexed attribute (and keep the default name in MongoDB) with the annotation. Is there a way to do it with the new bundle?

**Comment by nunomaduro** [comment]
@Cypaubr I am sorry. It's monday.  🙂

Using the function `normalize` you can archive that: https://www.algolia.com/doc/framework-integration/symfony/customizing/?language=laravel#using-normalize.
