### ISSUE TITLE
[Bug] Context Is Lost On Aggregation

### ISSUE THREAD

**Issue by kiler129** [algolia/search-bundle#286]
- Symfony version: 4.3.2
- Algolia Search Bundle version: master branch
- Algolia Client Version: irrelevant
- Language Version: irrelevant

### Description
While working on #283 implementation I discovered sometimes context is lost. I was able to track it down to these lines:

https://github.com/algolia/search-bundle/blob/d506f8443d83ae0da0ba32bdc30ad987a843c4ec/src/Entity/Aggregator.php#L89-L92

Is it intentional that format and other options (e.g. serialization groups) are ignored on this `normalize()` call? IMHO the code should NOT ignore them, since it will break custom normalizers.

**Comment by nunomaduro** [comment]
Thanks for this @kiler129, could this add some side-effects on people already using the search bundle (with this bug) ?

**Comment by kiler129** [comment]
@nunomaduro Basically no custom normalizers configured to support Algolia-related serialization will be invoked.

Imagine an aggregator with such definition:
```php
    public static function getEntities()
    {
        return [
            Post::class,
            Article::class
        ];
    }
```

Then you have such normalizer:
```php
class RandomNormalizer implements NormalizerInterface
{
    public function normalize($object, $format = null, array $context = [])
    {
        //... some logic
    }

    public function supportsNormalization($data, $format = null)
    {
        dump('Object type: ' . \get_class($data));
        dump('Format: ' . $format);
        dump('--');

        return $format === Searchable::NORMALIZATION_FORMAT && $data instanceof Post;
    }
}
```

**WITHOUT** my fix the condition in `supportsNormalization()` will never be hit. The output of import will be similar to this:
```
"Object type: App\Entity\LibraryThing"
"Format: searchableArray"
"--"
"Object type: App\Entity\Post"
"Format: "
"--"
Indexed 1 / 1 App\Entity\Post entities into dev_library index
"Object type: App\Entity\LibraryThing"
"Format: searchableArray"
"--"
"Object type: App\Entity\Article"
"Format: "
"--"
Indexed 1 / 1 App\Entity\Article entities into dev_library index
Done!
```

**WITH** my fix:
```
$ bin/console search:import
"Object type: App\Entity\LibraryThing"
"Format: searchableArray"
"--"
"Object type: App\Entity\Post"
"Format: searchableArray"
"--"
Indexed 1 / 1 App\Entity\Post entities into dev_library index
"Object type: App\Entity\LibraryThing"
"Format: searchableArray"
"--"
"Object type: App\Entity\Article"
"Format: searchableArray"
"--"
Indexed 1 / 1 App\Entity\Article entities into dev_library index
Done!
```

...and this is just `$format`, the same applies to any data in the `$context`.


Essentially aggregators, without the fix, makes impossible to use any custom normalizers only for Algolia on aggregated entities (since format & context is only passed for aggregator itself, not for inner entities).
