### ISSUE TITLE
Increase PHPStan level to 5

### ISSUE THREAD

**Issue by nunomaduro** [algolia/search-bundle#291]
Seems that PHPStan (`phpstan.neon.dist`) is analysing the project using the level 1, the **goal** here is bump the level until 5.

**Comment by kiler129** [comment]
Wouldn't be also helpful to incorporate PHPCS? The core with addition of https://github.com/slevomat/coding-standard is a great addition to almost any project increasing its quality dramatically.

**Comment by nunomaduro** [comment]
@kiler129 Yes. We have a issue created to study those tools: https://github.com/algolia/algoliasearch-client-php/issues/519

**Comment by chloelbn** [comment]
Those features have been added to our new [SearchBundle v4](https://github.com/algolia/search-bundle) 🎉 ! Don't hesitate and follow our [upgrade guide](https://github.com/algolia/search-bundle/blob/master/UPGRADE-4.0.md) to get acquainted with all the new features it proposes. It's still an alpha, so feedbacks are more than welcome!

Happy coding
