### ISSUE TITLE
Wrong Default Value Page On IndexManagerInterface

### ISSUE THREAD

**Issue by kiler129** [algolia/search-bundle#299]
- Symfony version: not relevant
- Algolia Search Bundle version: 3.4.0 / private fork
- Algolia Client Version: not relevant
- Language Version: not relevant

### Description
The `\Algolia\SearchBundle\IndexManagerInterface` specifies two methods containing default value for `$page` parameters - `search` and `rawSearch`.

This value is invalid according to Algolia - any attempt to query the engine with value of 0 produces the following error:
```json
{
  "message": "Invalid value for \"page\" parameter, expected integer >= 0",
  "status": 400
}
```

This is caused by `\Algolia\SearchBundle\Engine\EngineInterface` defining `$page` as `0` but also doing the following this in the default implementation of `search()`:
```php
$params = array_merge($parameters, [
            'hitsPerPage' => $nbResults,
            'page' => $page - 1,
        ]);
```

Is there any chance of cleaning this up, maybe in a next major with some warning for the time being? It's a split-brain situation where all docs are counting pages from 0, all interfaces are counting pages from 0 where engine implementation in Symfony unlike anything else counts them from 1.

**Comment by nunomaduro** [comment]
Thanks for this investigation, I also think that `0` makes no sense.

I aggree on this: `Is there any chance of cleaning this up, maybe in a next major with some warning for the time being? `.

Can you perform a pull request that adds phpdocs with a todo or similar?

**Comment by kiler129** [comment]
Sure, I can add such warning to the interface.

There's still the confusion of page numbering. Everywhere in the docs (e.g. https://www.algolia.com/doc/api-reference/api-parameters/page/?language=php#usage-notes) the first page is referred as `0` while Symfony bundle automatically makes pages one-base.

Is the Symfony bundle an exception? How does it look in other frameworks/languages which Algolia supports? (i.e. should this be a big-red-warning for Symfony bundle or generally it's half-half between languages :P)

**Comment by nunomaduro** [comment]
@kiler129 `Is the Symfony bundle an exception?` It's not. Is just a bug in our code:
```php
$params = array_merge($parameters, [
    'hitsPerPage' => $nbResults,
    'page' => $page - 1,
]);
```

The `- 1` should not be there. Please add a `@todo` using a Pull Request here we should address this on the next major version.

**Comment by chloelbn** [comment]
@kiler129 I'm closing this issue as it has been fixed in our new SearchBundle v4! Don't hesitate and check our [Upgrade Guide](https://github.com/algolia/search-bundle/blob/master/UPGRADE-4.0.md) to get acquainted with all the new features it offers, and don't hesitate to give us feedbacks! This is only an alpha version so feedbacks would be very much appreciated.

Thanks a lot!
