### ISSUE TITLE
[4.0] Upgrade to PHP Client dependency to ^2.2

### ISSUE THREAD

**Issue by nunomaduro** [algolia/search-bundle#301]
### Description

The search bundle is using the version `^1.0` if our PHP API Client. 

**Goal**: To resolve this issue, you should perform a pull request upgrading the PHP API Client dependency to `^2.2`.

**Comment by ZFLloyd** [comment]
I've started trying to do the upgrade, but I would like to know what is necessary to use the testsuite. I can run the tests but seems I am missing a few things.
