### ISSUE TITLE
[Question] Aggregator ETA

### ISSUE THREAD

**Issue by lolmx** [algolia/search-bundle#302]
Hello!

I just saw that aggregator supports has been added to master, gave a try and it works greatly.

I was wondering if you have an ETA for next release.

Regards,

**Comment by nunomaduro** [comment]
It's already included on the version 3.4: https://github.com/algolia/search-bundle/blob/master/CHANGELOG.md#340.

Enjoy! 🔥

**Comment by lolmx** [comment]
Oh didn't see, thanks 👍
