### ISSUE TITLE
Class 'Algolia\SearchBundle\Document\Aggregator' does not exist

### ISSUE THREAD

**Issue by Cypaubr** [algolia/search-bundle#304]
- Symfony version: 3.4.28
- Algolia Search Bundle version: 3.4.0
- Algolia Client Version: #.#.#
- Language Version:

### Description
Can't do nothing, just this error is raised:
`Class 'Algolia\SearchBundle\Document\Aggregator' does not exist`

### Steps To Reproduce
Install SearchBundle following the documentation.

**Comment by TomKlotzPro** [comment]
Hi @Cypaubr, thanks for reporting this issue.

I’ve tried to reproduce your step and I’m not able to raise your error, did you follow our [Documentation](https://www.algolia.com/doc/framework-integration/symfony/getting-started/)?

Don’t hesitate to tell us which part of our documentation you had troubles with to see together what can be your issue.

**Comment by Cypaubr** [comment]
Yes, I followed the documentation. But I guess the problem is caused by the fact I use Doctrine ODM not the ORM.

**Comment by martinfobian** [comment]
I'm having the same problem with the aggregator class missing. We are also using Doctrine ODM in our project, though we are not trying to index MongoDB documents, just ORM entities. As soon as I turn auto_mapping on for ODM, this error comes up. 

PHP 7.3.8
Symfony 3.4.30
Search Bundle 3.4

Any ideas how to get around this?

**Comment by neyric** [comment]
Got the same issue upgrading from 3.3.2 to 3.4.0. (also using Doctrine ODM)

It's probably caused by https://github.com/algolia/search-bundle/pull/257 , so we decided to stick with 3.3.3 for the time being...

**Comment by Cypaubr** [comment]
@neyric Did you created your own aggregator for using the ODM with search-client?
