### ISSUE TITLE
Weird output when indexing

### ISSUE THREAD

**Issue by tristanbes** [algolia/search-bundle#305]
Hello,

When indexing with `v3.4.0`, it outputs weird numbers, not a big issue though, but weird :)

<img width="567" alt="1__php_bin_console_search_import_--indices_cv_team_multigaming__ssh_" src="https://user-images.githubusercontent.com/346010/59194887-c34f1b80-8b8a-11e9-8f1a-76c054c06188.png">

**Comment by TomKlotzPro** [comment]
Hello Tristanbes,

Thanks for reporting this,

In fact, these are not weird numbers, it shows: for each batch of 500 entities, only X values are actually imported to Algolia.

Let me know if you have any other questions.

**Comment by tristanbes** [comment]
mhh, that explains why it's so random then. Thanks.
