### ISSUE TITLE
Useful catch_log_exceptions option is lost

### ISSUE THREAD

**Issue by ostrolucky** [algolia/search-bundle#311]
- Symfony version: 3.4.31
- Algolia Search Bundle version: 3.4.0
- Algolia Client Version: 1.28.0
- Language Version: PHP 7.3.9

### Description
We are migrating from 1.x and we noticed that since  https://github.com/algolia/search-bundle/commit/d443848a3bf5636876d0e34155b707f9f3f50018 there is no `algolia.catch_log_exceptions` option. 

This was useful for us, because developers now can't work offline (any entity update would trigger attempt to contact algolia server and exception raise).

**Comment by nunomaduro** [comment]
@ostrolucky You just to need to swap `AlgoliaEngine` by the `NullEngine`: https://www.algolia.com/doc/framework-integration/symfony/advanced/?language=php#about-the-nullengine.

**Comment by ostrolucky** [comment]
I mean idea was to just silence connection errors, not block all connection requests, even when dev is online. But meh, good enough for now to make dev configure this each time he needs to develop offline
