### ISSUE TITLE
Remove internal flag from Searchable class

### ISSUE THREAD

**Issue by ostrolucky** [algolia/search-bundle#313]
You can't mark this https://github.com/algolia/search-bundle/blob/a99f80b56601fc1dd6eea301f1cc57835149a7ad/src/Searchable.php#L6 internal and at the same time recommend to use it in your documentation https://www.algolia.com/doc/framework-integration/symfony/customizing/?language=php#handle-multiple-formats

**Comment by nunomaduro** [comment]
Thanks for this feedback - My colleague @chloelbn will handle your feedback next Monday. Thanks for your help!

**Comment by chloelbn** [comment]
Indeed, thanks a lot @ostrolucky ! I created a PR to fix that problem if you want to take a look: https://github.com/algolia/search-bundle/pull/314

Otherwise what are you thoughts on the v4? Are you satisfied with the new features? Was the upgrade difficult? Thanks a lot for your insights!

**Comment by ostrolucky** [comment]
We are upgrading from customized 1.x, so changes between 3. and 4. aren't very relevant for us. And we aren't done yet.
