### ISSUE TITLE
Groups support in JMS serializer

### ISSUE THREAD

**Issue by ostrolucky** [algolia/search-bundle#315]
- Symfony version: 3.4.32
- Algolia Search Bundle version: 4.0.0-alpha3

### Description

I would like to know what's the reason behind explicitly not supporting groups for JMS serializer in #225?

Maybe this is something that can be changed in version 4? We heavily use jms serializer in our project so we can't use default group. I can define different serializer service with default group defined, but it requires lot of configuration

**Comment by ostrolucky** [comment]
Actually this might cause an issue, because defining new serialization context for purpose of defining group would override default context, which doesn't define just default group, but also things like `shouldSerializeNull` option. Was this the reasoning in #225?

**Comment by julienbourdeau** [comment]
There is no real reason behind it to be honest. I had feedback about people using JMS serializer and I added compatibility. I was not very familiar with it and chose to only handle the most powerful use case (defining a Serializer class).

Maybe using Groups with JMS is a lot of work, maybe it's simple, I have no idea.
If you want to help, please feel free to send a PR.

Also, I want to say that we all really appreciate you testing the bundle in alpha version and opening issues your feedback 🙏 ❤️ 💯 Thanks a lot!

**Comment by ostrolucky** [comment]
Yeah I decided it's not worth to loose ability to use other default options like mentioned in https://github.com/algolia/search-bundle/issues/315#issuecomment-547818482. That's going to happen, because JMS requires defining whole new serialization context in order to define group to apply, like so
```php
return $this->normalizer->toArray(
  $this->entity,
  (new SerializationContext())->setGroups(Searchable:NORMALIZATION_GROUP)
);
```

For future travelers, here is how to configure serializer with own context to inject into algolia:
```xml
<service id="algolia_serializer" class="JMS\Serializer\Serializer">
    <argument type="service" id="jms_serializer.metadata_factory" />
    <argument type="collection">
        <argument type="service" key="1" id="jms_serializer.serialization_graph_navigator_factory" />
    </argument>
    <argument type="collection">
        <argument key="json" type="service" id="jms_serializer.json_serialization_visitor" />
    </argument>
    <argument type="collection" />
    <argument type="service">
        <service class="JMS\SerializerBundle\ContextFactory\ConfiguredContextFactory">
            <call method="setGroups">
                <argument type="collection">
                    <argument type="string">searchable</argument>
                </argument>
            </call>
            <call method="setSerializeNulls">
                <argument>true</argument>
            </call>
        </service>
    </argument>
    <argument type="service" id="jms_serializer.configured_deserialization_context_factory" />
    <argument type="service" id="jms_serializer.type_parser" />
</service>
```

Let's close
