### ISSUE TITLE
Handling relations in indexes

### ISSUE THREAD

**Issue by ostrolucky** [algolia/search-bundle#316]
- Symfony version: 3.4.32
- Algolia Search Bundle version: 4.0.0-alpha3

### Description
I can see there is still no kind of support for relations handling. As an example, we have index `user` and index `sedcard`, which is user's profile. So there is `ManyToOne` relation between `User` and `Sedcard`. 

Now, we do index some data from `User` in `sedcard` index, such as `username`. What we need is to update both indexes when `username` changes. 

Bundle listens to `postUpdate` event only though, which is not fired for Secard entity when User is changed, even though User embeds it (ManyToOne), so this doesn't work. To make matters worse, unlike `preUpdate`, `postUpdate` does not contain changeset, so hooking here does not allow to selectively index `sedcard` when only relevant parts of `user` change. 

There is some aggregator feature which is similar, but it's not quite what is needed here.

**Comment by chloelbn** [comment]
Hi @ostrolucky, thanks for your feedback. 

To put it simply, we prefer to let the end user handle on their side how their child relationship updates, as they're handling how they relate too. We can't know if an attribute from EntityA is used to serialize EntityB.
You can choose to either retrieve the related entities and update them manually when you update a parent, or try to take advantage of the [cascade:persist](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/working-with-associations.html#transitive-persistence-cascade-operations) annotation. 

If both those solutions are not satisfactory, would you mind giving us an example or a snippet of code showing a blocking situation, so we can have more details?

**Comment by ostrolucky** [comment]
Here's what I did in our project

```php
<?php

declare(strict_types = 1);

namespace AppBundle\Algolia;

use Algolia\SearchBundle\SearchServiceInterface;
use AppBundle\Document\User;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\EventSubscriber;
use Doctrine\ODM\MongoDB\Event\PreUpdateEventArgs;
use Doctrine\ODM\MongoDB\Events;
use function array_intersect;
use function array_keys;

final class RelationsAwareSubscriber implements EventSubscriber
{
    /**
     * @var array<string, array<callable, array<string>>>
     */
    private $relations = [];

    /**
     * @var SearchServiceInterface
     */
    private $decoratedSearchService;

    public function __construct(SearchServiceInterface $decoratedSearchService)
    {
        $this->decoratedSearchService = $decoratedSearchService;

        $this->relations = [
            User::class => [
                static function (User $user) {
                    return $user->getPersonalStylistSedcard();
                },
                ['username', 'about', 'legalInformation', 'chat', 'avatar'],
            ],
            User\LegalInformation::class => [
                static function (User\LegalInformation $legalInformation) {
                    return $legalInformation->getAllPublishedBlogArticles();
                },
                ['companyName', 'brandName'],
            ],
        ];
    }

    public function preUpdate(PreUpdateEventArgs $preUpdateEventArgs): void
    {
        $object = $preUpdateEventArgs->getObject();
        $objectManager = $preUpdateEventArgs->getObjectManager();
        $changeSet = $preUpdateEventArgs->getDocumentChangeSet();

        foreach ($this->relations as $class => [$getter, $fields]) {
            if (!$object instanceof $class || !array_intersect($fields, array_keys($changeSet))) {
                continue;
            }

            $relatedObject = $getter($object);

            if (!$relatedObject) {
                continue;
            }

            $this->decoratedSearchService->index(
                $objectManager,
                $relatedObject instanceof Collection ? $relatedObject->toArray() : $relatedObject
            );
        }
    }

    /**
     * @return string[]
     */
    public function getSubscribedEvents(): array
    {
        return [Events::preUpdate];
    }
}
```

In theory it would be possible to ship abstract version of this in algolia bundle, but unfortunately ODM and ORM don't share same interface for `PreUpdateEventArgs`, which makes this not ideal. Let's close for now.
