### ISSUE TITLE
Conflicts with Doctrine ODM?

### ISSUE THREAD

**Issue by Cypaubr** [algolia/search-bundle#326]
- Symfony version: 4.3.5
- Algolia Search Bundle version: 3.4.0
- Algolia Client Version: none
- Language Version: FR

### Description
When I install the bundle, composer sais it conflicts with Doctrine ODM Bundle. Why? MongoDB is still not supported by this bundle?

### Steps To Reproduce
Install both ODM bundle and Search Bundle.

**Comment by nunomaduro** [comment]
No. But the beta version, that will be become stable next week, already supports it! Do you mind of trying it out? Here tagged version of the beta is: `4.0.0-beta2`. You can install it using: 

```
composer require algolia/search-bundle:4.0.0-beta2
```

If you are using the v3, here is the upgrade guide: https://github.com/algolia/search-bundle/blob/master/UPGRADE-4.0.md.

**Comment by nunomaduro** [comment]
cc @chloelbn

**Comment by Cypaubr** [comment]
@nunomaduro Same issue with `4.0.0-beta2`

**Comment by chloelbn** [comment]
@Cypaubr could you tell me what bundle you're trying to install and what version please?

**Comment by Cypaubr** [comment]
@chloelbn `algolia/search-bundle:4.0.0-beta2` in a project using `"doctrine/mongodb-odm-bundle": "^4.0"`

**Comment by Cypaubr** [comment]
It seems to be working using the dev-master version. But I got another error in composer:
```
[KO]
Script cache:clear returned with error code 1
!!
!!  In MappingException.php line 106:
!!
!!    An error occurred in Algolia\SearchBundle\Document\Aggregator
!!
!!
!!  In ClassMetadata.php line 1953:
!!
!!    Property id does not exist
!!
!!
!!
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json to its original content.
```

**Comment by Cypaubr** [comment]
Any solution?

**Comment by Cypaubr** [comment]
@chloelbn I cleared the app cache, the composer cache, removed the `vendor/` then added `"algolia/search-bundle": "4.0.0-beta2"` to the composer.json and then installed the deps with `composer install -o`. After the installation, I added the line for the SearchBundle inside `bundles.php` and then tried to do` ./bin/composer cache:clear` and same error:
```
$ php bin/console cache:clear

In MappingException.php line 106:

  An error occurred in Algolia\SearchBundle\Document\Aggregator


In ClassMetadata.php line 1953:

  Property id does not exist
```
