### ISSUE TITLE
Unpublishing version 5.2.1 is breaking apps

### ISSUE THREAD

**Issue by keichinger** [algolia/search-bundle#367]
Hi,

I'm sorry for opening this issue, but this has happened to me now a couple of times (across this bundle and the JS libs), which is why I'm opening this issue here because it's the most recent one which has directly affected multiple projects of ours.

A couple of weeks ago (on 2022-02-10)  I was upgrading one of our projects from `algolia/search-bundle` v5.1.2 to v5.2.1, which worked flawlessly:

![CleanShot 2022-03-01 at 14 30 22](https://user-images.githubusercontent.com/439899/156179821-cdff5ba2-5eff-4d90-bce4-16dc2d3e2b75.png)

Now, three weeks later, I'm booting up the project again and I've been yelled at by Composer that this version is no longer matching my `minimum-stability` requirements — which is a difficult way for Composer to just tell me that this version does no longer exist, since it's no longer listed on the public Packagist repository (https://packagist.org/packages/algolia/search-bundle) nor here on GitHub as a Tag (https://github.com/algolia/search-bundle/tags) nor as a Release (https://github.com/algolia/search-bundle/releases).

I'm pretty sure there were reasons for unpublishing this version (even though I can't find any, and as a user I don't want to deep-dive into GitHub issues first before figuring out what was going on), though this move is actually breaking people's apps. And that's not even in an „oopsi”-way where there has been an accidental BC break: Publishing the apps has just stopped working for people out of the blue, which is the worst case scenario from an app's perspectivethat could happen to your dependencies.

I've noticed that there's now a v6.0.0 showing up on Packagist. Not sure what this one is about since it's for PHP >=8.0 only, while 5.2.1 was for PHP >=7.2, so it doesn't seem to be a direct replacement of some sorts?

However, I'd like to address this situation with some suggestions and requests directly to the maintainers:

1) If you ever run into a situation like that again, can you please just publish a new version (5.2.2 in that case) that fixes the previous versions mistakes?
2) If you still need to unpublish this version (for whatever reason), can you please inform people somewhere (e.g. within your changelog)?

If this all has been a huge mistake and was never the actual intention, then please excuse me if I sounded too harsh. I don't know any specifics, I'm just affected by a broken app :)

**Comment by DevinCodes** [comment]
Hi @keichinger ,

Thank you for opening the issue. Version 6 of the package adds support for the latest Symfony version, which requires dropping support for older PHP versions. So it's not a direct replacement of 5.2.1 indeed.

The 5.2.1 tag was inadvertently published due to a typo (it should have been 5.1.2). The 5.2.1 tag was immediately removed after it got pushed in favor of the correct one, but I'm guessing it got cached on Packagist anyway making it seem like it was available. If you change the version to 5.1.2 it should work again as expected. 

I'm sorry for the inconvenience this has caused. If it would help, I can publish version 5.2.1 and continue the versioning from there so that this issue doesn't occur anymore.

**Comment by keichinger** [comment]
Thanks @DevinCodes for responding ☺️ 
Personally, all of our apps have been reverted back to 5.1.2, so we're no longer affected.

I cannot speak for other people who might have been affected by this. I can only guess here on how many people might have explicitly restricted their apps to 5.2.1. The actual number could be very low or rather high - very hard to tell for me, especially since Packagist no longer shows the number of installations per version since this version has been removed: https://packagist.org/packages/algolia/search-bundle/stats#5.1.2

I also don't want to cause any unnecessary work :) If it's just adding a new tag on your side without any other overhead, then I'd say "sure, why not". If it's more than that, than it's totally up to you ✌️
